import { AiFillStar } from "react-icons/ai";
import hybridImage from './images/hybrid-2.webp';
import evolutionMXP from './images/evolution_MXP-02.jpeg';
import timoBollBlade from './images/blade_timo_boll_alc_fl_03.webp';
import nittakBlade from './images/nittaku-carbon-03.webp'
const data = [
  {
    img: hybridImage,
    title: "Tibhar Hybrid K3 Rubber",
    star: <AiFillStar className="rating-star" />,
    reviews: "(89 reviews)",
    prevPrice: "55.00",
    newPrice: "45",
    company: "Tibhar",
    color: "black",
    category: "rubber",
  },
  {
    img: nittakBlade,
    title: "Nittaku Premium 40+ Balls (Pack of 3)",
    star: <AiFillStar className="rating-star" />,
    reviews: "(267 reviews)",
    prevPrice: "12.00",
    newPrice: "10",
    company: "Nittaku",
    color: "white",
    category: "balls",
  },
  {
    img: evolutionMXP,
    title: "Tibhar Evolution MX-P Rubber",
    star: <AiFillStar className="rating-star" />,
    reviews: "(134 reviews)",
    prevPrice: "60.00",
    newPrice: "50",
    company: "Tibhar",
    color: "red",
    category: "rubber",
  },
  {
    img: timoBollBlade,
    title: "Butterfly Timo Boll ALC Blade",
    star: <AiFillStar className="rating-star" />,
    reviews: "(210 reviews)",
    prevPrice: "190.00",
    newPrice: "175",
    company: "Butterfly",
    color: "wood",
    category: "blade",
  },
  {
    img: hybridImage,
    title: "Butterfly Viscaria Blade",
    star: <AiFillStar className="rating-star" />,
    reviews: "(315 reviews)",
    prevPrice: "180.00",
    newPrice: "165",
    company: "Butterfly",
    color: "wood",
    category: "blade",
  },
  {
    img: hybridImage,
    title: "DHS 3-Star Table Tennis Balls (Pack of 6)",
    star: <AiFillStar className="rating-star" />,
    reviews: "(450 reviews)",
    prevPrice: "15.00",
    newPrice: "12",
    company: "DHS",
    color: "white",
    category: "balls",
  },
  {
    img: hybridImage,
    title: "Butterfly Centrefold 25 Table",
    star: <AiFillStar className="rating-star" />,
    reviews: "(98 reviews)",
    prevPrice: "1,800.00",
    newPrice: "1,750",
    company: "Butterfly",
    color: "blue",
    category: "table",
  },
  {
    img: hybridImage,
    title: "Stiga Advantage Indoor Table",
    star: <AiFillStar className="rating-star" />,
    reviews: "(157 reviews)",
    prevPrice: "500.00",
    newPrice: "470",
    company: "Stiga",
    color: "blue",
    category: "table",
  },
  {
    img: hybridImage,
    title: "Mizuno Wave Drive Table Tennis Shoes",
    star: <AiFillStar className="rating-star" />,
    reviews: "(200 reviews)",
    prevPrice: "130.00",
    newPrice: "120",
    company: "Mizuno",
    color: "red",
    category: "shoes",
  },
  {
    img: hybridImage,
    title: "Butterfly Lezoline Rifones Shoes",
    star: <AiFillStar className="rating-star" />,
    reviews: "(145 reviews)",
    prevPrice: "150.00",
    newPrice: "140",
    company: "Butterfly",
    color: "blue",
    category: "shoes",
  },
  {
    img: hybridImage,
    title: "Donic Carbotec 900 Pre-Assembled Bat",
    star: <AiFillStar className="rating-star" />,
    reviews: "(92 reviews)",
    prevPrice: "75.00",
    newPrice: "70",
    company: "Donic",
    color: "black",
    category: "bat",
  },
  {
    img: hybridImage,
    title: "Stiga Pro Carbon Pre-Assembled Bat",
    star: <AiFillStar className="rating-star" />,
    reviews: "(176 reviews)",
    prevPrice: "80.00",
    newPrice: "72",
    company: "Stiga",
    color: "black",
    category: "bat",
  },
  {
    img: hybridImage,
    title: "Butterfly Trolley Table Tennis Bag",
    star: <AiFillStar className="rating-star" />,
    reviews: "(67 reviews)",
    prevPrice: "95.00",
    newPrice: "85",
    company: "Butterfly",
    color: "black",
    category: "bag",
  },
  {
    img: hybridImage,
    title: "DHS Professional Table Tennis Net",
    star: <AiFillStar className="rating-star" />,
    reviews: "(120 reviews)",
    prevPrice: "35.00",
    newPrice: "30",
    company: "DHS",
    color: "blue",
    category: "net",
  },
  {
    img: hybridImage,
    title: "iPong V300 Table Tennis Robot",
    star: <AiFillStar className="rating-star" />,
    reviews: "(49 reviews)",
    prevPrice: "200.00",
    newPrice: "180",
    company: "iPong",
    color: "white",
    category: "robot",
  },
];

export default data;
